version: '3.3'

services:
  web:
    build: ./services/cstern.io
    command: gunicorn -w4 --bind 0.0.0.0:80 manage:app
    volumes:
      - /usr/src/app/
    ports:
      - 80:80
    env_file: 
      - ./.env.dev
    
