version: '3.7'

services:
  web:
    build: ./services/cstern.io
    command: gunicorn -w4 --bind 0.0.0.0:5000 manage:app
    volumes:
      - /usr/src/app/
    ports:
      - 5000:5000
    env_file: 
      - ./.env.dev
    
